### ISSUE TITLE
Works for one city but not for another

### ISSUE THREAD

**Issue by stalkerGH** [dragoon/cityliner#1]
Hi @dragoon

Thank you for nice GTFS plotter! I'm playing with it and ancountered a problem. Cityliner works with data for one city but not for another one. I tried to eliminate bumps step by step but without success. 

I'm interested in plotting maps for Warszawa and Wroclaw. I've downloaded GTFS files from transitfeeds.com. First I tried with Warszawa, everything goes smoothly. Then Wroclaw - and I always stop with error:

> DEBUG:root:GTFS provider: gtfs/wroclaw
> DEBUG:root:Render area: 9933 x 14043 px
> DEBUG:root:Center coordinates: Point(lat=51.0, lon=17.0)
> DEBUG:root:Max distance from center: 0.7073274941251869x1km
> DEBUG:root:Computing GTFS segments data...
> DEBUG:root:Starting route types iteration...
> DEBUG:root:Finished route type iteration
> DEBUG:root:Total routes: 129
> DEBUG:root:Starting trip iteration...
> Traceback (most recent call last):
>   File "/home/stalker/Projekty/Git/cityliner/main.py", line 46, in <module>
>     process_gtfs_trips(center_point=Point(center_lat, center_lon), out_dir=out_dir, gtfs_dir=args.gtfs,
>   File "/home/stalker/Projekty/Git/cityliner/citylines/trip_extractor.py", line 55, in process_gtfs_trips
>     segments = dataset.compute_segments(center_point, render_area, max_dist)
>   File "/home/stalker/Projekty/Git/cityliner/citylines/gtfs/gtfs.py", line 86, in compute_segments
>     route_types, trips_on_a_shape = self._get_trips_and_routes()
>   File "/home/stalker/Projekty/Git/cityliner/citylines/gtfs/gtfs.py", line 64, in _get_trips_and_routes
>     for shape_id, route_id in self._parse_trips():
>   File "/home/stalker/Projekty/Git/cityliner/citylines/gtfs/gtfs.py", line 30, in _parse_trips
>     route_id = row["route_id"]
> KeyError: 'route_id'

What have I done so far:

1) checked format of routes.txt,
2) checked typos in routes.txt
3) checked routes.txt for doubled `route_id`
4) removed all files except of routes.txt, shapes.txt, trips.txt (this minimal set works for Warszawa)
5) removed all columns except two (`route_id,route_type`) from routes.txt (this method works for Warszawa)

What can I do more?

**Comment by dragoon** [comment]
Hi @stalkerGH, I think the problem might be that there is a route_id in ``trips.txt`` that is not present in ``routes.txt``. It's a data quality issue, but I will make a change to ignore such cases.

Can you give me direct links to the datasets you are using?

**Comment by stalkerGH** [comment]
Thank you for quick reply. Here are the sources (direct links):

Warszawa -> https://mkuran.pl/gtfs/warsaw.zip
Wrocław -> https://www.wroclaw.pl/open-data/87b09b32-f076-4475-8ec9-6020ed1f9ac0/OtwartyWroclaw_rozklad_jazdy_GTFS.zip

**Comment by dragoon** [comment]
I fixed the error with the Wroclaw files -- they used UTF-8 encoding with BOM, now the script determines the encoding automatically, but there is still some issues with the data, the generated poster doesn't look right. Maybe the share sequences are not in the right order. I need some time to investigate whether this can be fixed.

You can also try to check this dataset on some online GTFS checkers to see if there are any issues.

**Comment by stalkerGH** [comment]
Thank you for checks and fixes. You're right about "broken" encoding - viewing the file routes.txt in Transitfeeds.com shows strange characters in the begining of first line: https://transitfeeds.com/p/mpk-wroc-aw/663/latest/file/routes.txt. The same for other files but I understand that is no more the issue.

Generated poster looks "not good" (maybe good as art but not the map). I checked whole ZIP archive, report is available here: 
https://gtfs-validator-results.mobilitydata.org/6ac78f15-4301-4b83-8f09-0f1546198d3a/report.html but with my limited knowledge I don't see anything suspicious here.

**Comment by dragoon** [comment]
@stalkerGH found the issues, ``shapes.txt`` was not sorted according to the specification, but I added sorting inside my code to account for such cases. Draws Wroclaw correctly now.
Feel free to create a PR to add city/transport company logos for those cities.

**Comment by stalkerGH** [comment]
Thank you very much for resolving this issue. It seems that I had "a blessing in disguise" by finding the (only?) city with dirty GTFS data :) My quick test shows that the routes are drawn as expected but I'll do more test with different radius later today. I'll try to create PR - I've never done this before.
