### ISSUE TITLE
Logo available but not visible on poster

### ISSUE THREAD

**Issue by stalkerGH** [dragoon/cityliner#2]
Generated posters have no logos visible. I checked for Helsinki (example from README) and for Wrocław - all files are present in their directories. I see no additional option for enable/disable them. What should I check?

EDIT: What are configurations of cities in _process_configs.py_ for? Maybe an additional option could be added (for example `use_config` or similar) for `main.py` to read from config instead of command line?

**Comment by dragoon** [comment]
@stalkerGH sorry, I forgot to update the docs, you need to specify logos as a separate argument:`` --logos "gemeente_amsterdam.svg" "gvb.svg"``, they will be read from the ``./assets/logos/{place_name}/``.
You can see it if you run ``--help`` command

**Comment by stalkerGH** [comment]
Works! Thank you :)
